version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_data:/data/db
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=sqlite:////data/db/db.sqlite3
    depends_on:
      - nginx

  nginx:
    image: nginx:1.23-alpine
    restart: always
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web

  s3sync:
    image: amazon/aws-cli:latest
    restart: unless-stopped
    volumes:
      - sqlite_data:/data/db
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: >
      sh -c "
        while true; do
          aws s3 sync /data/db s3://${S3_BUCKET_NAME}/db/
          sleep ${BACKUP_INTERVAL:-3600}
        done
      "

volumes:
  static_volume:
  media_volume:
  sqlite_data: