version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - sqlite_data:/data/db
    environment:
      - DEBUG=0
      - SECRET_KEY=${SECRET_KEY:-your_default_secret_key}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - DATABASE_URL=sqlite:////data/db/db.sqlite3
      # AWS S3 settings
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME:-your-bucket-name}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:1.23-alpine
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates if using HTTPS
    ports:
      - "80:80"
      - "443:443"  # For HTTPS
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  s3sync:
    image: amazon/aws-cli:latest
    restart: unless-stopped
    volumes:
      - sqlite_data:/data/db
      - media_volume:/app/media
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    command: >
      sh -c "
        # First sync media files to S3
        if [ ! -z \"$AWS_ACCESS_KEY_ID\" ] && [ ! -z \"$AWS_SECRET_ACCESS_KEY\" ] && [ ! -z \"$AWS_STORAGE_BUCKET_NAME\" ]; then
          echo 'Syncing media files to S3...'
          aws s3 sync /app/media s3://${AWS_STORAGE_BUCKET_NAME:-your-bucket-name}/media/
        fi
        
        # Then sync database files periodically
        while true; do
          aws s3 sync /data/db s3://${S3_BUCKET_NAME:-my-backup-bucket}/db/
          sleep ${BACKUP_INTERVAL:-3600}
        done
      "
    depends_on:
      - web

  # Optional: Backup service for SQLite database
  backup:
    image: alpine:latest
    restart: unless-stopped
    volumes:
      - sqlite_data:/data/db:ro
      - ./backups:/backups
    command: |
      sh -c 'cp /data/db/db.sqlite3 /backups/db-$$(date +%Y%m%d-%H%M%S).sqlite3 && 
             find /backups -name "db-*.sqlite3" -mtime +7 -delete && 
             sleep 86400 && while true; do
               cp /data/db/db.sqlite3 /backups/db-$$(date +%Y%m%d-%H%M%S).sqlite3;
               find /backups -name "db-*.sqlite3" -mtime +7 -delete;
               sleep 86400;
             done'
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  sqlite_data: