# Generated by Django 3.2 on 2025-04-24 07:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20211126_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('materialId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('materialHeading', models.CharField(max_length=100)),
                ('materialDescription', models.TextField()),
                ('materialType', models.CharField(max_length=50)),
                ('materialLink', models.TextField(blank=True, null=True)),
                ('materialFile', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('publishedTime', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.classroom')),
            ],
        ),
    ]
